"""add_installation_cost_and_updated_by_to_quotes

Revision ID: 005abf4fb72f
Revises: 09c3f0569d3a
Create Date: 2026-08-02 19:09:12.894109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005abf4fb72f'
down_revision: Union[str, None] = '09c3f0569d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


installation_cost_type_enum = sa.Enum('fixed', 'percentage', name='installationcosttype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    installation_cost_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('quotes', sa.Column('installation_cost_type', installation_cost_type_enum, nullable=True))
    op.add_column('quotes', sa.Column('installation_cost_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('quotes', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quotes_updated_by_id'), 'quotes', ['updated_by_id'], unique=False)
    op.create_foreign_key(None, 'quotes', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_quotes_updated_by_id'), table_name='quotes')
    op.drop_column('quotes', 'updated_by_id')
    op.drop_column('quotes', 'installation_cost_value')
    op.drop_column('quotes', 'installation_cost_type')
    installation_cost_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
