"""add_supplies_and_supply_variants

Revision ID: 35cb4c80ac4a
Revises: 05e79b44bd97
Create Date: 2026-09-11 18:57:04.367848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35cb4c80ac4a'
down_revision: Union[str, None] = '05e79b44bd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The `ivarate` enum type was already created by f3a1c9d4e6b2 (products.iva_rate).
# create_type=False stops SQLAlchemy from re-issuing `CREATE TYPE ivarate` here,
# which would fail with DuplicateObjectError against an existing DB.
iva_rate_enum = postgresql.ENUM('iva_0', 'iva_10_5', 'iva_21', name='ivarate', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('iva_rate', iva_rate_enum, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_supplies_name_active', 'supplies', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('supply_variants',
    sa.Column('supply_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_supply_variant_price_non_negative'),
    sa.CheckConstraint('stock_qty >= 0', name='ck_supply_variant_stock_non_negative'),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supply_id', 'sku', name='uq_supply_variant_supply_sku')
    )
    op.create_index(op.f('ix_supply_variants_supply_id'), 'supply_variants', ['supply_id'], unique=False)
    op.create_index('uq_supply_variant_sku_active', 'supply_variants', ['sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_supply_variant_sku_active', table_name='supply_variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_supply_variants_supply_id'), table_name='supply_variants')
    op.drop_table('supply_variants')
    op.drop_index('uq_supplies_name_active', table_name='supplies', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('supplies')
    # ### end Alembic commands ###
