"""replace_package_option_groups_with_catalog_items

Revision ID: 7108e0395600
Revises: 8241345e7e00
Create Date: 2026-09-26 20:54:03.855678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7108e0395600'
down_revision: Union[str, None] = '8241345e7e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_items',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('product', 'supply', name='packageitemkind'), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('supply_variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'product' AND product_variant_id IS NOT NULL AND supply_variant_id IS NULL) OR (kind = 'supply' AND supply_variant_id IS NOT NULL AND product_variant_id IS NULL)", name='ck_package_item_kind_matches_variant'),
    sa.CheckConstraint('quantity > 0', name='ck_package_item_quantity_positive'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['supply_variant_id'], ['supply_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_items_package_id'), 'package_items', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_items_product_variant_id'), 'package_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_package_items_supply_variant_id'), 'package_items', ['supply_variant_id'], unique=False)
    op.drop_index(op.f('ix_package_options_group_id'), table_name='package_options')
    op.drop_table('package_options')
    op.drop_index(op.f('ix_package_option_groups_package_id'), table_name='package_option_groups')
    op.drop_table('package_option_groups')
    # op.add_column with an inline Enum does NOT auto-create the Postgres
    # type the way create_table does — create it explicitly first.
    package_pricing_mode = postgresql.ENUM('final_price', 'discount_percent', name='packagepricingmode')
    package_pricing_mode.create(op.get_bind(), checkfirst=True)
    # Added nullable, backfilled, then tightened: a NOT NULL column without a
    # default fails on a table that already has rows. Legacy packages keep
    # their old base_price as a fixed final price (floored to satisfy the
    # pricing_value > 0 check); they have no items yet, so they stay hidden
    # from the storefront until an admin rebuilds them.
    op.add_column('packages', sa.Column('pricing_mode', package_pricing_mode, nullable=True))
    op.add_column('packages', sa.Column('pricing_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute(
        "UPDATE packages SET pricing_mode = 'final_price', "
        "pricing_value = GREATEST(COALESCE(base_price, 0), 0.01)"
    )
    op.alter_column('packages', 'pricing_mode', nullable=False)
    op.alter_column('packages', 'pricing_value', nullable=False)
    op.drop_constraint(op.f('ck_package_base_price_non_negative'), 'packages', type_='check')
    op.create_check_constraint('ck_package_pricing_value_positive', 'packages', 'pricing_value > 0')
    op.drop_column('packages', 'base_price')
    op.drop_column('packages', 'complexity')
    # complexity's enum type is orphaned by drop_column (Postgres doesn't
    # drop it implicitly) — remove it explicitly, as required by this
    # migration's brief.
    op.execute("DROP TYPE IF EXISTS packagecomplexity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the enum type explicitly — op.add_column with an inline
    # postgresql.ENUM does NOT auto-create the type the way create_table
    # does (SQLAlchemy only hooks that in via before_create table events).
    package_complexity = postgresql.ENUM('basico', 'medio', 'avanzado', name='packagecomplexity')
    package_complexity.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'packages',
        sa.Column('complexity', package_complexity, autoincrement=False, nullable=False, server_default='basico'),
    )
    op.add_column(
        'packages',
        sa.Column('base_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, server_default='0'),
    )
    op.alter_column('packages', 'complexity', server_default=None)
    op.alter_column('packages', 'base_price', server_default=None)
    op.drop_constraint('ck_package_pricing_value_positive', 'packages', type_='check')
    op.create_check_constraint(op.f('ck_package_base_price_non_negative'), 'packages', 'base_price >= 0::numeric')
    op.drop_column('packages', 'pricing_value')
    op.drop_column('packages', 'pricing_mode')
    op.execute("DROP TYPE IF EXISTS packagepricingmode")
    op.create_table('package_option_groups',
    sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('package_option_groups_package_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('package_option_groups_pkey'))
    )
    op.create_index(op.f('ix_package_option_groups_package_id'), 'package_option_groups', ['package_id'], unique=False)
    op.create_table('package_options',
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('price_delta', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['package_option_groups.id'], name=op.f('package_options_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('package_options_pkey'))
    )
    op.create_index(op.f('ix_package_options_group_id'), 'package_options', ['group_id'], unique=False)
    op.drop_index(op.f('ix_package_items_supply_variant_id'), table_name='package_items')
    op.drop_index(op.f('ix_package_items_product_variant_id'), table_name='package_items')
    op.drop_index(op.f('ix_package_items_package_id'), table_name='package_items')
    op.drop_table('package_items')
    op.execute("DROP TYPE IF EXISTS packageitemkind")
    # ### end Alembic commands ###
