"""add_quotes_module

Revision ID: 754eb890c80c
Revises: fb4f80ab5b2c
Create Date: 2026-06-13 18:04:03.411698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754eb890c80c'
down_revision: Union[str, None] = 'fb4f80ab5b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('quotes',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=50), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('borrador', 'enviada', 'aprobada', 'rechazada', 'vencida', name='quotestatus'), nullable=False),
    sa.Column('cost_notes', sa.Text(), nullable=True),
    sa.Column('margin_notes', sa.Text(), nullable=True),
    sa.Column('internal_comments', sa.Text(), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_consultation_id'), 'quotes', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_quotes_created_by_id'), 'quotes', ['created_by_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('product', 'service', name='quoteitemkind'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=300), nullable=True),
    sa.Column('product_sku_snapshot', sa.String(length=100), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hourly_rate_snapshot', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_quote_id'), 'quote_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###
    # Seed default hourly rate
    op.execute("INSERT INTO app_settings (key, value) VALUES ('hourly_rate', '5000') ON CONFLICT (key) DO NOTHING")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_items_quote_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_quotes_created_by_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_consultation_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
