"""add_image_url_to_supplies

Revision ID: acfb66d3b286
Revises: 7108e0395600
Create Date: 2026-09-26 21:11:36.716607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfb66d3b286'
down_revision: Union[str, None] = '7108e0395600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'image_url')
    # ### end Alembic commands ###
